zabbix:
  host: "api-utrrippay"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "https://api.utrip.cloud/utrippay/health"
    '{$CERT.WEBSITE.IP}': ""
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "https://api.utrip.cloud/utrippay/health"
          status_codes: "200"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site https://api.utrip.cloud/utrippay/health indisponivel"
      expression: "last(/api-utrrippay/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5