zabbix:
  host: "dli-frontend-sso"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "https://trial.minhabiblioteca.com.br/Login.aspx?key=API_KEY_2"
    '{$CERT.WEBSITE.IP}': "127.0.0.1"
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "https://trial.minhabiblioteca.com.br/Login.aspx?key=API_KEY_2"
          status_codes: "201"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site https://trial.minhabiblioteca.com.br/Login.aspx?key=API_KEY_2 indisponivel"
      expression: "last(/dli-frontend-sso/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5