zabbix:
  host: "flower"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "flower.minhabiblioteca.com.br"
    '{$CERT.WEBSITE.IP}': ""
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "flower.minhabiblioteca.com.br"
          status_codes: "200"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site flower.minhabiblioteca.com.br indisponivel"
      expression: "last(/flower/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5