zabbix:
  host: "fusion-detalhes-livro"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "https://fusion.minhabiblioteca.com.br/contents/api/v1/books/40aa8fed-c8ad-463c-8669-a6ee2489e721"
    '{$CERT.WEBSITE.IP}': "127.0.0.1"
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "https://fusion.minhabiblioteca.com.br/contents/api/v1/books/40aa8fed-c8ad-463c-8669-a6ee2489e721"
          status_codes: "200"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site https://fusion.minhabiblioteca.com.br/contents/api/v1/books/40aa8fed-c8ad-463c-8669-a6ee2489e721 indisponivel"
      expression: "last(/fusion-detalhes-livro/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5