zabbix:
  host: "fusion-ultimas-leitura"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "https://fusion.minhabiblioteca.com.br/contents/api/v1/last_books"
    '{$CERT.WEBSITE.IP}': "127.0.0.1"
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "https://fusion.minhabiblioteca.com.br/contents/api/v1/last_books"
          status_codes: "200"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site https://fusion.minhabiblioteca.com.br/contents/api/v1/last_books indisponivel"
      expression: "last(/fusion-ultimas-leitura/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5