zabbix:
  host: "minhabiblioteca-site"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "https://minhabiblioteca.com.br"
    '{$CERT.WEBSITE.IP}': "127.0.0.1"
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "https://minhabiblioteca.com.br"
          status_codes: "201"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site https://minhabiblioteca.com.br indisponivel"
      expression: "last(/minhabiblioteca-site/web.test.fail[Check https://minhabiblioteca.com.br],#3)=1"
      priority: 5