zabbix:
  host: "odoo-minhabiblioteca"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "http://odoo.minhabiblioteca.com.br/"
    '{$CERT.WEBSITE.IP}': "127.0.0.1"
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "http://odoo.minhabiblioteca.com.br/"
          status_codes: "201"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site http://odoo.minhabiblioteca.com.br/ indisponivel"
      expression: "last(/odoo-minhabiblioteca/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5