zabbix:
  host: "odoo-health"
  groups:
    - groupid: "22"
  macros:
    '{$CERT.WEBSITE.HOSTNAME}': "https://conecta.minhabiblioteca.com.br/web/health"
    '{$CERT.WEBSITE.IP}': "127.0.0.1"
  web_scenarios:
    - name: "Check Authenticated URL"
      delay: "5m"
      retries: "1"
      agent: "Zabbix"
      steps:
        - name: "Step Web"
          url: "https://conecta.minhabiblioteca.com.br/web/health"
          status_codes: "201"
          timeout: "15s"
          no: 1
  triggers:
    - name: "Site https://conecta.minhabiblioteca.com.br/web/health indisponivel"
      expression: "last(/odoo-health/web.test.fail[Check Authenticated URL],#3)=1"
      priority: 5